services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=file:./data/apps.db
    volumes:
      - ./data:/app/data